#!/usr/bin/env python3
"""Script para gerar o registro expandido de serviços AWS."""

from src.domain.entities.resource import ResourceType

# Categor ização de serviços
CATEGORY_MAP = {
    "COMPUTE": ["EC2", "LAMBDA", "ECS", "EKS", "FARGATE", "BATCH", "LIGHTSAIL", "ELASTIC_BEANSTALK", "APP_RUNNER", "OUTPOSTS", "LOCAL_ZONES", "WAVELENGTH", "SERVERLESS_APPLICATION_REPOSITORY", "VMWARE_CLOUD", "PARALLEL_CLUSTER"],
    "STORAGE": ["S3", "EBS", "EFS", "FSX", "GLACIER", "BACKUP", "STORAGE_GATEWAY", "ELASTIC_DISASTER_RECOVERY", "FILE_CACHE"],
    "DATABASE": ["RDS", "AURORA", "DYNAMODB", "ELASTICACHE", "MEMORYDB", "REDSHIFT", "DOCUMENTDB", "NEPTUNE", "QLDB", "TIMESTREAM", "KEYSPACES", "DAX"],
    "NETWORKING": ["VPC", "CLOUDFRONT", "ROUTE53", "API_GATEWAY", "DIRECT_CONNECT", "APP_MESH", "CLOUD_MAP", "GLOBAL_ACCELERATOR", "ELB", "ALB", "NLB", "GATEWAY_LOAD_BALANCER", "PRIVATE_LINK", "TRANSIT_GATEWAY", "CLIENT_VPN", "SITE_TO_SITE_VPN", "CLOUD_WAN", "PRIVATE_5G", "VPC_LATTICE", "VERIFIED_ACCESS"],
    "ANALYTICS": ["ATHENA", "EMR", "KINESIS", "MSK", "GLUE", "DATA_PIPELINE", "LAKE_FORMATION", "QUICKSIGHT", "OPENSEARCH_SERVICE", "DATA_EXCHANGE", "CLEAN_ROOMS", "FINSPACE"],
    "APPLICATION": ["SQS", "SNS", "SES", "APPSYNC", "EVENTBRIDGE", "STEP_FUNCTIONS", "SWF", "MQ", "MANAGED_APACHE_AIRFLOW", "APPFLOW", "B2BI"],
    "AI_ML": ["SAGEMAKER", "BEDROCK", "TEXTRACT", "REKOGNITION", "COMPREHEND", "TRANSLATE", "TRANSCRIBE", "POLLY", "LEX", "FORECAST", "PERSONALIZE", "FRAUD_DETECTOR", "KENDRA", "CODEWHISPERER", "AMAZON_Q", "LOOKOUT_METRICS", "LOOKOUT_VISION", "LOOKOUT_EQUIPMENT", "MONITRON", "HEALTHLAKE", "AUGMENTED_AI", "DEVOPS_GURU"],
    "DEVELOPER_TOOLS": ["CODECOMMIT", "CODEBUILD", "CODEDEPLOY", "CODEPIPELINE", "CODESTAR", "CODECATALYST", "CODEGURU", "CODEARTIFACT", "CLOUD9", "CLOUDSHELL", "X_RAY", "APPLICATION_COMPOSER", "FAULT_INJECTION_SIMULATOR", "MICROSERVICE_EXTRACTOR", "PROTON", "COPILOT_CLI"],
    "SECURITY": ["IAM", "COGNITO", "SECRETS_MANAGER", "KMS", "CLOUDHSM", "CERTIFICATE_MANAGER", "WAF", "SHIELD", "GUARDDUTY", "MACIE", "INSPECTOR", "DETECTIVE", "SECURITY_HUB", "AUDIT_MANAGER", "FIREWALL_MANAGER", "NETWORK_FIREWALL", "VERIFIED_PERMISSIONS", "PRIVATE_CERTIFICATE_AUTHORITY", "DIRECTORY_SERVICE", "PAYMENT_CRYPTOGRAPHY", "SIGNER", "SECURITY_LAKE", "ARTIFACT"],
    "MANAGEMENT": ["CLOUDWATCH", "CLOUDTRAIL", "CONFIG", "SYSTEMS_MANAGER", "CLOUDFORMATION", "SERVICE_CATALOG", "TRUSTED_ADVISOR", "CONTROL_TOWER", "LICENSE_MANAGER", "ORGANIZATIONS", "RESOURCE_GROUPS", "TAG_EDITOR", "MANAGED_GRAFANA", "MANAGED_PROMETHEUS", "OPSWORKS", "CHATBOT", "LAUNCH_WIZARD", "RESILIENCE_HUB", "INCIDENT_MANAGER", "SERVICE_MANAGEMENT_CONNECTOR", "APP_CONFIG"],
    "MIGRATION": ["MIGRATION_HUB", "APPLICATION_MIGRATION_SERVICE", "DATABASE_MIGRATION_SERVICE", "DMS_FLEET_ADVISOR", "DATASYNC", "TRANSFER_FAMILY", "MIGRATION_EVALUATOR", "SNOW_FAMILY", "SNOWCONE", "MAINFRAME_MODERNIZATION"],
    "BUSINESS": ["CONNECT", "PINPOINT", "CHIME", "WORKMAIL", "WORKDOCS", "AMPLIFY", "ALEXA_FOR_BUSINESS", "SUPPLY_CHAIN", "WICKR"],
    "END_USER_COMPUTING": ["WORKSPACES", "APPSTREAM"],
    "IOT": ["IOT_CORE", "IOT_GREENGRASS", "IOT_ANALYTICS", "IOT_DEVICE_MANAGEMENT", "IOT_DEVICE_DEFENDER", "IOT_EVENTS", "IOT_SITEWISE", "IOT_TWINMAKER", "IOT_FLEETWISE", "IOT_ROBORUNNER", "IOT_1CLICK", "IOT_BUTTON", "IOT_EDUKIT", "IOT_EXPRESSLINK", "FREERTOS"],
    "ROBOTICS": ["ROBOMAKER"],
    "MEDIA": ["ELASTIC_TRANSCODER", "ELEMENTAL_MEDIACONVERT", "ELEMENTAL_MEDIALIVE", "ELEMENTAL_MEDIAPACKAGE", "ELEMENTAL_MEDIASTORE", "ELEMENTAL_MEDIATAILOR", "ELEMENTAL_MEDIACONNECT", "INTERACTIVE_VIDEO_SERVICE", "NIMBLE_STUDIO"],
    "GAME": ["GAMELIFT", "GAMESPARKS", "LUMBERYARD"],
    "AR_VR": ["SUMERIAN", "AR_VR", "SIMSPACE_WEAVER"],
    "BLOCKCHAIN": ["MANAGED_BLOCKCHAIN", "QUANTUM_LEDGER_DATABASE"],
    "QUANTUM": ["BRAKET"],
    "SATELLITE": ["GROUND_STATION"],
    "COST_MANAGEMENT": ["COST_EXPLORER", "COST_AND_USAGE_REPORT", "BUDGETS", "COST_ANOMALY_DETECTION", "SAVINGS_PLANS", "BILLING_CONDUCTOR", "MARKETPLACE"],
    "CUSTOMER_ENABLEMENT": ["IQ", "SUPPORT", "MANAGED_SERVICES"],
}

def find_category(service_name):
    """Encontra a categoria de um serviço."""
    for cat, services in CATEGORY_MAP.items():
        if service_name in services or any(s in service_name for s in services):
            return cat
    return "MANAGEMENT"

# Contagens
total = 0
by_category = {}

for rt in ResourceType:
    if rt in [ResourceType.GENERIC, ResourceType.UNKNOWN]:
        continue
    
    cat = find_category(rt.name)
    if cat not in by_category:
        by_category[cat] = 0
    by_category[cat] += 1
    total += 1

print(f"Total de serviços a serem registrados: {total}")
print("\nPor categoria:")
for cat in sorted(by_category.keys()):
    print(f"  {cat:25s}: {by_category[cat]:3d} serviços")

# Gerar código Python para o registro
print("\n\nTOTAL A SEREM ADICIONADOS AO REGISTRO: {} serviços".format(total - 83))
print("(83 já estão no registro atual)")

